// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plsoahiyucxutzzeqpdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsc29haGl5dWN4dXR6emVxcGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mzc4NDMsImV4cCI6MjA2NzAxMzg0M30.dEgCvvF_nkoL04lBCX5qg6WGq8lY_ZdyuOLAIVFMX9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});